INQSkill = INQSkill || {};
//list of accepted skills
INQSkill.skills = [
  {Name: "Acrobatics",      DefaultStat: "Ag"},
  {Name: "Athletics",       DefaultStat: "S"},
  {Name: "Awareness",       DefaultStat: "Per"},
  {Name: "Barter",          DefaultStat: "Fe"},
  {Name: "Blather",         DefaultStat: "Fe"},
  {Name: "Carouse",         DefaultStat: "T"},
  {Name: "Charm",           DefaultStat: "Fe"},
  {Name: "Chem-Use",        DefaultStat: "It"},
  {Name: "Ciphers",         DefaultStat: "It"},
  {Name: "Climb",           DefaultStat: "S"},
  {Name: "Commerce",        DefaultStat: "Fe"},
  {Name: "Command",         DefaultStat: "Fe"},
  {Name: "Common Lore",     DefaultStat: "It"},
  {Name: "Concealment",     DefaultStat: "Ag"},
  {Name: "Contortionist",   DefaultStat: "Ag"},
  {Name: "Deceive",         DefaultStat: "Fe"},
  {Name: "Demolition",      DefaultStat: "It"},
  {Name: "Disguise",        DefaultStat: "It"},
  {Name: "Dodge",           DefaultStat: "Ag"},
  {Name: "Drive",           DefaultStat: "Ag"},
  {Name: "Evaluate",        DefaultStat: "It"},
  {Name: "Forbidden Lore",  DefaultStat: "It"},
  {Name: "Gamble",          DefaultStat: "It"},
  {Name: "Inquiry",         DefaultStat: "Fe"},
  {Name: "Interrogation",   DefaultStat: "It"},
  {Name: "Intimidate",      DefaultStat: "S"},
  {Name: "Invocation",      DefaultStat: "Wp"},
  {Name: "Literacy",        DefaultStat: "It"},
  {Name: "Logic",           DefaultStat: "It"},
  {Name: "Medicae",         DefaultStat: "It"},
  {Name: "Navigation",      DefaultStat: "It"},
  {Name: "Performer",       DefaultStat: "Fe"},
  {Name: "Pilot",           DefaultStat: "Ag"},
  {Name: "Psyniscience",    DefaultStat: "Per"},
  {Name: "Scholastic Lore", DefaultStat: "It"},
  {Name: "Scrutiny",        DefaultStat: "Per"},
  {Name: "Search",          DefaultStat: "Per"},
  {Name: "Secret Tongue",   DefaultStat: "It"},
  {Name: "Security",        DefaultStat: "It"},
  {Name: "Shadowing",       DefaultStat: "Ag"},
  {Name: "Silent Move",     DefaultStat: "Ag"},
  {Name: "Sleight of Hand", DefaultStat: "Ag"},
  {Name: "Speak Language",  DefaultStat: "It"},
  {Name: "Survival",        DefaultStat: "It"},
  {Name: "Swim",            DefaultStat: "S"},
  {Name: "Tactics",         DefaultStat: "It"},
  {Name: "Tech-Use",        DefaultStat: "It"},
  {Name: "Tracking",        DefaultStat: "It"},
  {Name: "Trade",           DefaultStat: "Ag"},
  {Name: "Wrangling",       DefaultStat: "Fe"}
];
